POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Rodrigo Fontes",
  "email": "rodrigo@gmail.com",
  "password": "123123123"
}

###

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "rodrigo@gmail.com",
  "password": "123123123"
}

###

GET http://localhost:3333/me
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYmU4ZTRiYS0zMGYzLTRkODAtOGE0NC1iMjQwYzUyZDFiNWEiLCJpYXQiOjE3MTg2MjgxMDV9.RoHfZihxbzaNF_wq-YnVEUBqFQD7jE7WmxxKtlomdNE